name: flutter_built_bloc
version: 0.3.4
author: Alo√Øs Deniel <alois.deniel@outlook.com>
description: Generates the BLoC boilerplate.
homepage: https://github.com/aloisdeniel/built_bloc

environment:
  sdk: '>=2.0.0-dev <3.0.0' 
 
dependencies:
  built_bloc: ^0.3.4
  provider: ^1.6.1  
  flutter: 
    sdk: flutter 
 
dev_dependencies: 
  flutter_test:
    sdk: flutter

dependency_overrides:
  built_bloc:
    path: ../built_bloc